#!/usr/bin/env bash

# Apple
alias dsclean='find . -name .DS_Store -type f -print -delete'
alias xclean='xattr -c'

# AWS
alias lsbucket='aws s3 ls s3://samkennerly/'

# Bash
alias la='ls -Gla'
alias myip='dig +short myip.opendns.com @resolver1.opendns.com'
export PS1="\[\e[32m\]\u\]\[\e[36m\]@\h\]\n\[\e[31m\]\w/\[\e[m\]"

# Black
alias blackbox="$HOME/code/blackbox/blackbox"

# Docker
dockerbash="$HOME/code/dockerbash"
alias drbake="$dockerbash/bin/bake"
alias drclean="$dockerbash/bin/clean"
alias drdelete="$dockerbash/bin/delete"
alias drkill="$dockerbash/bin/kill"
alias drrunit="$dockerbash/bin/runit"
alias drshow="$dockerbash/bin/show"

# Git
alias githero='git log --graph --decorate --simplify-by-decoration --all'
alias gitshow='git fetch --all; git branch --list --all; git status;'
alias gittree='git ls-tree -r --full-tree --name-only HEAD'

# Openers
alias readcsv="open -a 'Easy CSV Editor'"
alias readhex="open -a 'Hex Fiend'"
alias readjson="open -a 'JSON Editor'"
alias readmd="open -a 'Marked 2'"

# Python
alias applepy='/usr/bin/python'
alias condapy='/usr/local/anaconda3/bin/python'
alias condapip='/usr/local/anaconda3/bin/pip'
alias python2='/usr/local/bin/python2'
alias python3='/usr/local/bin/python3'
alias pip2='/usr/local/bin/pip2'
alias pip3='/usr/local/bin/pip3'

# Q
export QHOME="$HOME/q"
alias q='rlwrap --complete-filenames --remember "$QHOME"/m32/q'

# https://github.com/nvbn/thefuck
eval "$(thefuck --alias)"
