#!/usr/bin/env bash

# AWS
alias lsbucket='aws s3 ls s3://samkennerly/'

# Bash
alias la='ls -Gla'
alias myip='dig +short myip.opendns.com @resolver1.opendns.com'
export PS1="\[\e[32m\]\u\]\[\e[36m\]@\h\]\n\[\e[31m\]\w/\[\e[m\]"

# Docker
dockerbash="$HOME/code/dockerbash"
alias dockerbake="$dockerbash/bin/bake"
alias dockerclean="$dockerbash/bin/clean"
alias dockerdelete="$dockerbash/bin/delete"
alias dockerkill="$dockerbash/bin/kill"
alias dockerrunit="$dockerbash/bin/runit"
alias dockershow="$dockerbash/bin/show"

# Git
alias githero='git log --graph --decorate --simplify-by-decoration --all'
alias gitshow='git fetch --all; git branch --list --all; git status;'
alias gittree='git ls-tree -r --full-tree --name-only HEAD'

# Kingofsnake
kos="$HOME/code/kingofsnake"
alias runlab="$kos/bin/runlab"

# Openers
alias editcsv="open -a 'Easy CSV Editor'"
alias editjson="open -a 'JSON Editor'"
alias hex-fiend="open -a 'Hex Fiend'"
alias macdown="open -a 'MacDown'"

# Python
alias applepy='/usr/bin/python'
alias condapy='/usr/local/anaconda3/bin/python'
alias condapip='/usr/local/anaconda3/bin/pip'
alias python2='/usr/local/bin/python2'
alias python3='/usr/local/bin/python3'
alias pip2='/usr/local/bin/pip2'
alias pip3='/usr/local/bin/pip3'

# Q
export QHOME="$HOME/q"
alias q="rlwrap -c -r '$QHOME'/m32/q"

# Ruby
eval "$(rbenv init -)"

# https://github.com/nvbn/thefuck
eval "$(thefuck --alias)"
