#!/usr/bin/env sh

alias la='ls -Gla'
alias myip='dig +short myip.opendns.com @resolver1.opendns.com'
export PS1="\[\e[32m\]\u\]\[\e[36m\]@\h\]\n\[\e[31m\]\w/\[\e[m\]"

# Apple
alias dsclean='find . -name .DS_Store -type f -print -delete'
alias xclean='xattr -c'

# AWS
alias lsbucket='aws s3 ls'

# Docker
dockerbash="$HOME/code/dockerbash"
alias drbake="$dockerbash/bin/bake"
alias drclean="$dockerbash/bin/clean"
alias drdelete="$dockerbash/bin/delete"
alias drkill="$dockerbash/bin/kill"
alias drrunit="$dockerbash/bin/runit"
alias drshow="$dockerbash/bin/show"

# Git
alias githero='git log --graph --decorate --simplify-by-decoration --all'
alias gitshow='git fetch --all; git branch --list --all; git status;'
alias gittree='git ls-tree -r --full-tree --name-only HEAD'

# Java
alias javas='/usr/libexec/java_home --verbose'

# Python
alias applepy='/usr/bin/python'
alias blackbox="$HOME/code/blackbox/blackbox"
alias condapy='/usr/local/anaconda3/bin/python'
alias condapip='/usr/local/anaconda3/bin/pip'

# Q
export QHOME="$HOME/q"
alias q='rlwrap --complete-filenames --remember "$QHOME"/m32/q'

# Readers
alias readcsv="open -a 'Easy CSV Editor'"
alias readhex="open -a 'Hex Fiend'"
alias readjson="open -a 'JSON Editor'"
alias readmd="open -a 'Marked 2'"

# https://github.com/nvbn/thefuck
eval "$(thefuck --alias)"
